### ISSUE TITLE
can't open or load texture phase_3/maps/eyes.jpg

### ISSUE THREAD

**Issue by sebby09559** [OpenToontownTools/TTOpenLevelEditor#16]
can you fix this error?

**Comment by drewc5131** [comment]
This is not an error with the editor. Odds are you didn't even insert the resource files needed.

**Comment by sebby09559** [comment]
where was i ment to get the files


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
